from Parser import Parser

if __name__ == '__main__':
    parser = Parser()
    parser.set_command("push local 2")
    parser.parse()
    print(parser.get_type())
    print(parser.get_command())
    print(parser.get_segment_label())
    print(parser.get_address())
    print(parser.get_operation())
    parser.set_command("pop \tconstant   4\t\t")
    parser.parse()
    print(parser.get_type())
    print(parser.get_command())
    print(parser.get_segment_label())
    print(parser.get_address())
    print(parser.get_operation())
    parser.set_command("  add   local 2 //fdsffs")
    parser.parse()
    print(parser.get_type())
    print(parser.get_command())
    print(parser.get_segment_label())
    print(parser.get_address())
    print(parser.get_operation())
    parser.set_command("  //fsfsfs")
    parser.parse()
    print(parser.get_type())
    print(parser.get_command())
    print(parser.get_segment_label())
    print(parser.get_address())
    print(parser.get_operation())
